%% Add paths

codeRoot = "/userdata/dxu/project_np/code";

addpath( ...
    genpath(fullfile(codeRoot, "third_party_matlab/npy-matlab")), ...
    genpath(fullfile(codeRoot, "third_party_matlab/ManyFunMatlab")), ...
    genpath(fullfile(codeRoot, "third_party_matlab/mPraat")), ...
    fullfile(codeRoot, "np_preproc"), ...
    fullfile(codeRoot, "np_preproc/neural"), ...
    fullfile(codeRoot, "np_preproc/se"), ...
    fullfile(codeRoot, "mtracer"), ...
    fullfile(codeRoot, "mtracer/external/neuropixel-utils"), ...
    genpath(fullfile(codeRoot, "babble")), ...
    genpath(fullfile(codeRoot, "semsr_np")) ...
    );
