%% Add paths

addpath( ...
    genpath("/userdata/dxu/project_np/code/third_party_matlab/Kilosort-2.5-server"), ...
    genpath("/userdata/dxu/project_np/code/third_party_matlab/npy-matlab"), ...
    genpath("/userdata/dxu/project_np/code/third_party_matlab/ManyFunMatlab"), ...
    genpath("/userdata/dxu/project_np/code/third_party_matlab/mPraat"), ...
    genpath("/userdata/dxu/project_np/code/np_preproc/"), ...
    "/userdata/dxu/project_np/code/mtracer", ...
    "/userdata/dxu/project_np/code/mtracer/external/neuropixel-utils", ...
    "/userdata/dxu/project_np/code/babble" ...
    );
